<?php

return [
    '001' => [
        'name' => 'Kerajaan',
        'agencies' => [
            ['code' => 'K010100', 'name' => 'Jabatan Perdana Menteri (JPM)'],
            ['code' => 'A010101', 'name' => 'Suruhanjaya Pilihan Raya (SPR)'],
            ['code' => 'A010102', 'name' => 'Suruhanjaya Pencegahan Rasuah Malaysia (SPRM)'],
            ['code' => 'A010103', 'name' => 'Jabatan Kemajuan Islam Malaysia (JAKIM)'],
            ['code' => 'A010104', 'name' => 'Perbadanan Putrajaya (PPj)'],
            ['code' => 'A010105', 'name' => 'Parlimen Malaysia'],
            ['code' => 'A010106', 'name' => 'Suruhanjaya Perkhidmatan Pendidikan (SPP)'],
            ['code' => 'A010107', 'name' => 'Jabatan Perkhidmatan Awam (JPA)'],
            ['code' => 'A010108', 'name' => 'Pejabat Ketua Pendaftar Mahkamah Persekutuan Malaysia'],
            ['code' => 'A010109', 'name' => 'Bahagian Kabinet, Perlembagaan dan Perhubungan Antara Kerajaan'],
            ['code' => 'A010110', 'name' => 'Pejabat Perdana Menteri (PMO)'],
            ['code' => 'A010111', 'name' => 'Jabatan Peguam Negara (AGC)'],
            ['code' => 'K010200', 'name' => 'Jabatan Digital Negara (JDN)'],
            ['code' => 'A010201', 'name' => 'Kementerian Belia dan Sukan (KBS)'],
            ['code' => 'A010202', 'name' => 'Kementerian Perumahan dan Kerajaan Tempatan (KPKT)'],
            ['code' => 'A010203', 'name' => 'Kementerian Luar Negeri (KLN)'],
            ['code' => 'A010204', 'name' => 'Kementerian Kerja Raya (KKR)'],
            ['code' => 'A010205', 'name' => 'Kementerian Pendidikan Tinggi (KPT)'],
            ['code' => 'A010206', 'name' => 'Kementerian Perpaduan Negara (KPN)'],
            ['code' => 'A010207', 'name' => 'Kementerian Pembangunan Wanita, Keluarga dan Masyarakat (KPWKM)'],
            ['code' => 'A010208', 'name' => 'Kementerian Pendidikan Malaysia (KPM)'],
            ['code' => 'A010209', 'name' => 'Kementerian Pelancongan, Seni dan Budaya (MOTAC)'],
            ['code' => 'A010210', 'name' => 'Kementerian Sumber Asli dan Kelestarian Alam (NRES)'],
            ['code' => 'A010211', 'name' => 'Kementerian Sumber Manusia (KESUMA)'],
            ['code' => 'A010212', 'name' => 'Kementerian Kemajuan Desa dan Wilayah (KKDW)'],
            ['code' => 'A010213', 'name' => 'Pertubuhan Keselamatan Sosial (PERKESO)'],
            ['code' => 'A010214', 'name' => 'Institut Penyelidikan Perhutanan Malaysia (FRIM)'],
            ['code' => 'A010215', 'name' => 'Perbadanan Tabung Pembangunan Kemahiran (PTPK)'],
            ['code' => 'A010216', 'name' => 'Jabatan Pembangunan Kemahiran (JPK)'],
            ['code' => 'A010217', 'name' => 'Jabatan Ukur dan Pemetaan (JUPEM)'],
            ['code' => 'A010218', 'name' => 'Jabatan Kesihatan dan Keselamatan Pekerja (JKKP)'],
            ['code' => 'K010300', 'name' => 'Pejabat Setiausaha Kerajaan Johor'],
            ['code' => 'K010400', 'name' => 'Pejabat Setiausaha Kerajaan Negeri Kedah'],
            ['code' => 'K010500', 'name' => 'Pejabat Setiausaha Kerajaan Negeri Kelantan'],
            ['code' => 'K010600', 'name' => 'Pejabat Setiausaha Kerajaan Negeri Melaka'],
            ['code' => 'K010700', 'name' => 'Pejabat Setiausaha Kerajaan Negeri Negeri Sembilan'],
            ['code' => 'A010701', 'name' => 'Majlis Bandaraya Seremban'],
            ['code' => 'A010702', 'name' => 'Pejabat Kewangan dan Perbendaharaan Negeri Sembilan'],
            ['code' => 'A010703', 'name' => 'Pejabat Tanah dan Galian Negeri Sembilan'],
            ['code' => 'A010704', 'name' => 'Majlis Agama Islam Negeri Sembilan (MAINS)'],
            ['code' => 'A010705', 'name' => 'Majlis Perbandaran Port Dickson'],
            ['code' => 'K010800', 'name' => 'Pejabat Setiausaha Kerajaan Negeri Pahang'],
            ['code' => 'A010801', 'name' => 'Majlis Bandaraya Kuantan'],
            ['code' => 'A010802', 'name' => 'Pejabat Kewangan dan Perbendaharaan Negeri Pahang'],
            ['code' => 'A010803', 'name' => 'Pejabat Pengarah Tanah dan Galian Pahang'],
            ['code' => 'K010900', 'name' => 'Pejabat Setiausaha Kerajaan Negeri Perak'],
            ['code' => 'K011000', 'name' => 'Pejabat Setiausaha Kerajaan Negeri Perlis'],
            ['code' => 'A011001', 'name' => 'Pejabat Perbendaharaan Negeri Perlis'],
            ['code' => 'A011002', 'name' => 'Pejabat Pengarah Tanah dan Galian Negeri Perlis'],
            ['code' => 'K011100', 'name' => 'Pejabat Setiausaha Kerajaan Negeri Pulau Pinang'],
            ['code' => 'K011200', 'name' => 'Pejabat Setiausaha Kerajaan Negeri Sabah'],
            ['code' => 'K011300', 'name' => 'Pejabat Setiausaha Kerajaan Negeri Sarawak'],
            ['code' => 'A011301', 'name' => 'Sarawak Information System Sdn.Bhd.(SAINS)'],
            ['code' => 'K011400', 'name' => 'Pejabat Setiausaha Kerajaan Negeri Selangor'],
            ['code' => 'A011401', 'name' => 'Perbendaharaan Negeri Selangor'],
            ['code' => 'A011402', 'name' => 'Pejabat Tanah dan Galian Negeri Selangor'],
            ['code' => 'K011500', 'name' => 'Pejabat Setiausaha Kerajaan Negeri Terengganu'],
        ],
    ],
    '002' => [
        'name' => 'Perbankan dan Kewangan',
        'agencies' => [
            ['code' => 'K020100', 'name' => 'Kementerian Kewangan Malaysia (MOF)'],
            ['code' => 'A020101', 'name' => 'Jabatan Kastam DiRaja Malaysia (JKDM)'],
            ['code' => 'A020102', 'name' => 'Jabatan Akauntan Negara Malaysia'],
            ['code' => 'A020103', 'name' => 'Jabatan Penilaian dan Perkhidmatan Harta'],
            ['code' => 'A020104', 'name' => 'Lembaga Hasil Dalam Negeri (LHDN)'],
            ['code' => 'A020105', 'name' => 'Kumpulan Wang Simpanan Pekerja'],
            ['code' => 'A020106', 'name' => 'Kumpulan Wang Persaraan (Diperbadankan)'],
            ['code' => 'A020107', 'name' => 'Lembaga Pembiayaan Perumahan Sektor Awam (LPPSA)'],
            ['code' => 'A020108', 'name' => 'Lembaga Perkhidmatan Kewangan Labuan'],
            ['code' => 'K020200', 'name' => 'Bank Negara Malaysia (BNM)'],
            ['code' => 'A020201', 'name' => 'Malayan Banking Berhad'],
            ['code' => 'A020202', 'name' => 'CIMB Bank Berhad'],
            ['code' => 'A020203', 'name' => 'Public Bank Berhad'],
            ['code' => 'A020204', 'name' => 'PayNet - Malaysian Electronic Payment System'],
            ['code' => 'A020205', 'name' => 'BSN Malaysia'],
            ['code' => 'A020206', 'name' => 'Touch n\' Go'],
            ['code' => 'A020207', 'name' => 'TNG Digital Sdn. Bhd.'],
            ['code' => 'K020300', 'name' => 'Suruhanjaya Sekuriti Malaysia'],
            ['code' => 'A020301', 'name' => 'Bursa Malaysia'],
        ],
    ],
    '003' => [
        'name' => 'Pengangkutan',
        'agencies' => [
            ['code' => 'K030100', 'name' => 'Kementerian Pengangkutan Malaysia (MOT)'],
            ['code' => 'A030101', 'name' => 'Jabatan Pengangkutan Jalan (JPJ) Malaysia'],
            ['code' => 'A030102', 'name' => 'Jabatan Laut Malaysia (JLM)'],
            ['code' => 'A030103', 'name' => 'Lembaga Pelabuhan Kelang (LPK)'],
            ['code' => 'A030104', 'name' => 'Lembaga Pelabuhan Johor (LPJ)'],
            ['code' => 'A030105', 'name' => 'Lembaga Pelabuhan Kuantan (LPKtn)'],
            ['code' => 'A030106', 'name' => 'Lembaga Pelabuhan Kemaman (LPKmn)'],
            ['code' => 'A030107', 'name' => 'Lembaga Pelabuhan Bintulu (LPB)'],
            ['code' => 'K030200', 'name' => 'Pihak Berkuasa Penerbangan Awam Malaysia (CAAM)'],
            ['code' => 'A030201', 'name' => 'Malindo Airways Sdn Bhd (Batik Air Malaysia)'],
            ['code' => 'A030202', 'name' => 'Malaysia Airports Holdings Berhad'],
            ['code' => 'A030203', 'name' => 'Pos Aviation Sdn. Bhd.'],
            ['code' => 'A030204', 'name' => 'Malaysia Aviation Group (MAG)'],
            ['code' => 'A030205', 'name' => 'Capital A Berhad'],
            ['code' => 'A030206', 'name' => 'Ground Team Red Sdn.Bhd'],
            ['code' => 'A030207', 'name' => 'AirAsia X Berhad'],
            ['code' => 'A030208', 'name' => 'AirAsia Berhad'],
            ['code' => 'A030209', 'name' => 'Senai Airport Terminal Services Sdn.Bhd.'],
            ['code' => 'K030300', 'name' => 'Agensi Pengangkutan Awam Darat (APAD)'],
            ['code' => 'A030301', 'name' => 'Rapid Rail'],
            ['code' => 'A030302', 'name' => 'Keretapi Tanah Melayu Berhad (KTMB)'],
            ['code' => 'A030303', 'name' => 'Express Rail Link (ERL)'],
            ['code' => 'A030304', 'name' => 'Rapid Bus'],
            ['code' => 'A030305', 'name' => 'Prasarana Malaysia Berhad'],
            ['code' => 'K030400', 'name' => 'Lembaga Lebuhraya Malaysia (LLM)'],
            ['code' => 'A030401', 'name' => 'Projek Lebuhraya Usahasama Berhad (PLUS)'],
            ['code' => 'A030402', 'name' => 'Amanat Lebuhraya Rakyat Berhad (LITRAK)'],
            ['code' => 'A030403', 'name' => 'BESRAYA (M) Sdn. Bhd'],
            ['code' => 'A030404', 'name' => 'Grand Saga Sdn Bhd'],
            ['code' => 'A030405', 'name' => 'Jambatan Kedua Sdn Bhd'],
            ['code' => 'A030406', 'name' => 'Konsortium Lebuhraya Utara - Timur (KL) Sdn Bhd (DUKE)'],
            ['code' => 'A030407', 'name' => 'KL-Kuala Selangor Expressway Berhad (LATAR)'],
            ['code' => 'A030408', 'name' => 'Lebuhraya Kajang - Seremban Sdn Bhd (LEKAS)'],
            ['code' => 'A030409', 'name' => 'Lingkaran Luar Butterworth (Penang) Sdn Bhd'],
            ['code' => 'A030410', 'name' => 'Lebuhraya Pantai Timur 2 Sdn Bhd (LPT2)'],
            ['code' => 'A030411', 'name' => 'Maju Expressway Sdn Bhd (MEX)'],
            ['code' => 'A030412', 'name' => 'New Pantai Expressway Sdn. Bhd. (NPE)'],
            ['code' => 'A030413', 'name' => 'Senai Desaru Expressway Berhad'],
            ['code' => 'A030414', 'name' => 'Projek Lintasan Kota Holding Sdn. Bhd.'],
        ],
    ],
    '004' => [
        'name' => 'Pertahanan dan Keselamatan',
        'agencies' => [
            ['code' => 'K040100', 'name' => 'Kementerian Dalam Negeri (KDN)'],
            ['code' => 'A040101', 'name' => 'Polis Diraja Malaysia (PDRM)'],
            ['code' => 'A040102', 'name' => 'Agensi Penguatkuasaan Maritim Malaysia (APMM)'],
            ['code' => 'A040103', 'name' => 'Jabatan Imigresen Malaysia (JIM)'],
            ['code' => 'A040104', 'name' => 'Jabatan Pendaftaran Negara (JPN)'],
            ['code' => 'A040105', 'name' => ' Jabatan Pendaftaran Pertubuhan Malaysia (JPPM)'],
            ['code' => 'A040106', 'name' => 'Agensi Kawalan dan Perlindungan Sempadan Malaysia (AKPS)'],
            ['code' => 'K040200', 'name' => 'Kementerian Pertahanan Malaysia (MINDEF)'],
            ['code' => 'A040201', 'name' => 'Jabatan Hal Ehwal Veteran (JHEV)'],
            ['code' => 'A040202', 'name' => 'Lembaga Tabung Angkatan Tentera (LTAT)'],
            ['code' => 'K040300', 'name' => 'Angkatan Tentera Malaysia (Bahagian Siber dan Elektromagnetik Pertahanan (BSEP)'],
        ],
    ],
    '005' => [
        'name' => 'Maklumat, Komunikasi dan Digital',
        'agencies' => [
            ['code' => 'K050100', 'name' => 'Kementerian Komunikasi'],
            ['code' => 'A050101', 'name' => 'Jabatan Penyiaran Malaysia (RTM)'],
            ['code' => 'A050102', 'name' => ' Jabatan Penerangan Malaysia (JAPEN)'],
            ['code' => 'A050103', 'name' => 'Pertubuhan Berita Nasional Malaysia (BERNAMA)'],
            ['code' => 'A050104', 'name' => 'Perbadanan Kemajuan Filem Nasional Malaysia (FINAS)'],
            ['code' => 'K050200', 'name' => 'Kementerian Digital'],
            ['code' => 'A050201', 'name' => 'Jabatan Perlindungan Data Peribadi (JPDP)'],
            ['code' => 'A050202', 'name' => 'CyberSecurity Malaysia (CSM)'],
            ['code' => 'K050300', 'name' => 'Suruhanjaya Komunikasi dan Multimedia Malaysia (MCMC)'],
            ['code' => 'A050301', 'name' => 'CelcomDigi Berhad'],
            ['code' => 'A050302', 'name' => 'Maxis Berhad'],
            ['code' => 'A050303', 'name' => 'U Mobile Sdn. Bhd.'],
            ['code' => 'A050304', 'name' => 'TIME Dotcom Berhad'],
            ['code' => 'A050305', 'name' => 'Telekom Malaysia Berhad'],
            ['code' => 'A050306', 'name' => 'Digital Nasional Berhad (DNB)'],
            ['code' => 'A050307', 'name' => 'Fibrecomm Network (M) Sdn Bhd'],
            ['code' => 'A050308', 'name' => 'MEASAT Satellite Systems Sdn Bhd'],
            ['code' => 'A050309', 'name' => 'MYIX (Malaysian Internet Exchange)'],
            ['code' => 'A050310', 'name' => 'MYNIC Berhad'],
            ['code' => 'A050311', 'name' => 'NTT MSC Sdn Bhd'],
            ['code' => 'A050312', 'name' => 'Shinjiru Technology Sdn Bhd'],
        ],
    ],
    '006' => [
        'name' => 'Tenaga',
        'agencies' => [
            ['code' => 'K060100', 'name' => 'Kementerian Peralihan Tenaga dan Transformasi Air (PETRA)'],
            ['code' => 'A060101', 'name' => 'Pihak Berkuasa Pembangunan Tenaga Lestari (SEDA)'],
            ['code' => 'K060200', 'name' => 'Suruhanjaya Tenaga'],
            ['code' => 'A060201', 'name' => 'Tenaga Nasional Berhad'],
            ['code' => 'A060202', 'name' => 'Gas Malaysia Distribution Sdn Bhd'],
            ['code' => 'A060203', 'name' => 'NUR Power'],
            ['code' => 'A060204', 'name' => 'Malakoff Corporation Berhad'],
            ['code' => 'A060205', 'name' => 'Edra Energy Sdn Bhd'],
            ['code' => 'A060206', 'name' => 'Jimah O&M Sdn Bhd'],
            ['code' => 'A060207', 'name' => 'Kapar Energy Venture Sdn Bhd'],
            ['code' => 'A060208', 'name' => 'Kuala Langat Power Plant Sdn Bhd'],
            ['code' => 'A060209', 'name' => 'Musteq Hydro Sdn Bhd'],
            ['code' => 'K060300', 'name' => 'Jabatan Tenaga Atom (Atom Malaysia)'],
            ['code' => 'A060301', 'name' => 'Agensi Nuklear Malaysia'],
            ['code' => 'K060400', 'name' => 'Petroliam Nasional Berhad (PETRONAS)'],
            ['code' => 'A060401', 'name' => 'Malaysian Refining Company Sdn. Bhd. (MRCSB)'],
            ['code' => 'A060402', 'name' => 'Malaysia LNG Sdn. Bhd. (MLNG)'],
        ],
    ],
    '007' => [
        'name' => 'Air, Pembentungan dan Pengurusan Sisa',
        'agencies' => [
            ['code' => 'K070100', 'name' => 'Suruhanjaya Perkhidmatan Air Negara (SPAN)'],
            ['code' => 'A070101', 'name' => 'Pengurusan Air Pahang Berhad (PAIP)'],
            ['code' => 'A070102', 'name' => 'Syarikat Air Perlis Sdn Bhd (SAP)'],
            ['code' => 'A070103', 'name' => 'Syarikat Air Negeri Sembilan Sdn Bhd (SAINS)'],
            ['code' => 'A070104', 'name' => 'Syarikat Air Darul Aman (SADA)'],
            ['code' => 'A070105', 'name' => 'Syarikat Air Melaka Berhad (SAMB)'],
            ['code' => 'A070106', 'name' => 'Ranhill SAJ Sdn. Bhd.'],
            ['code' => 'A070107', 'name' => 'Perbadanan Bekalan Air Pulau Pinang (PBAPP)'],
            ['code' => 'A070108', 'name' => 'Air Kelantan Sdn Bhd (AKSB)'],
            ['code' => 'A070109', 'name' => 'Pengurusan Air Selangor Sdn. Bhd.'],
            ['code' => 'A070110', 'name' => 'Syarikat Air Terengganu Sdn. Bhd. (SATU)'],
            ['code' => 'A070111', 'name' => 'Lembaga Air Perak (LAP)'],
            ['code' => 'A070112', 'name' => 'Indah Water Konsortium Sdn. Bhd. (IWK)'],
            ['code' => 'A070113', 'name' => 'Bahagian Bekalan Air Labuan'],
            ['code' => 'A070114', 'name' => 'Pengurusan Aset Air Berhad'],
            ['code' => 'K070200', 'name' => 'Perbadanan Pengurusan Sisa Pepejal dan Pembersihan Awam (SWCorp)'],
            ['code' => 'A070201', 'name' => 'Alam Flora Sdn. Bhd.'],
            ['code' => 'A070202', 'name' => 'Southern Waste Management Sdn. Bhd. (SWM Environment Sdn. Bhd.)'],
            ['code' => 'A070203', 'name' => 'Environment Idaman Sdn. Bhd.'],
            ['code' => 'K070300', 'name' => 'Kementerian Peralihan Tenaga dan Transformasi Air (PETRA)'],
            ['code' => 'A070301', 'name' => 'Jabatan Pengairan dan Saliran (JPS)'],
            ['code' => 'A070302', 'name' => 'Institut Penyelidikan Hidraulik Kebangsaan Malaysia (NAHRIM)'],
        ],
    ],
    '008' => [
        'name' => 'Pertanian dan Perladangan',
        'agencies' => [
            ['code' => 'K080100', 'name' => 'Kementerian Pertanian dan Keterjaminan Makanan'],
            ['code' => 'A080101', 'name' => 'Jabatan Pertanian Malaysia (DOA)'],
            ['code' => 'A080102', 'name' => 'Jabatan Perikanan Malaysia (DOF)'],
            ['code' => 'A080103', 'name' => 'Jabatan Perkhidmatan Veterinar (DVS)'],
            ['code' => 'A080104', 'name' => 'Jabatan Perkhidmatan Kuarantin dan Pemeriksaan Malaysia (MAQIS)'],
            ['code' => 'K080200', 'name' => 'Kementerian Perladangan dan Komoditi'],
            ['code' => 'A080201', 'name' => 'Lembaga Minyak Sawit Malaysia (MPOB)'],
            ['code' => 'A080202', 'name' => 'Lembaga Getah Malaysia (LGM)'],
            ['code' => 'A080203', 'name' => 'Lembaga Perindustrian Kayu Malaysia (MTIB)'],
            ['code' => 'A080204', 'name' => 'Lembaga Koko Malaysia (LKM)'],
            ['code' => 'A080205', 'name' => 'Lembaga Lada Malaysia (MPB)'],
            ['code' => 'A080206', 'name' => 'Lembaga Kenaf dan Tembakau Negara (LKTN)'],
        ],
    ],
    '009' => [
        'name' => 'Perdagangan, Industri dan Ekonomi',
        'agencies' => [
            ['code' => 'K090100', 'name' => 'Kementerian Pelaburan, Perdagangan dan Industri (MITI)'],
            ['code' => 'A090101', 'name' => 'Lembaga Pembangunan Pelaburan Malaysia (Malaysian Investment Development Authority, MIDA)'],
            ['code' => 'A090102', 'name' => 'Institut Piawaian dan Penyelidikan Perindustrian Malaysia (SIRIM)'],
            ['code' => 'A090103', 'name' => 'Jabatan Standard Malaysia (Department of Standards Malaysia, JSM)'],
            ['code' => 'K090200', 'name' => 'Kementerian Perdagangan Dalam Negeri dan Kos Sara Hidup (KPDN)'],
            ['code' => 'A090201', 'name' => 'Suruhanjaya Syarikat Malaysia (SSM)'],
            ['code' => 'A090202', 'name' => 'Perbadanan Harta Intelek Malaysia (MyIPO)'],
            ['code' => 'K090300', 'name' => 'Kementerian Ekonomi'],
            ['code' => 'A090301', 'name' => 'Jabatan Perangkaan Malaysia (DOSM)'],
            ['code' => 'K090400', 'name' => 'Kementerian Pembangunan Usahawan dan Koperasi (KUSKOP)'],
            ['code' => 'A090401', 'name' => 'Suruhanjaya Koperasi Malaysia'],
            ['code' => 'A090402', 'name' => 'Institut Koperasi Malaysia'],
            ['code' => 'A090403', 'name' => 'SME Corp Malaysia'],
            ['code' => 'A090404', 'name' => 'Tekun Nasional'],
            ['code' => 'A090405', 'name' => 'Institut Keusahawanan Negara'],
            ['code' => 'A090406', 'name' => 'Bank Rakyat'],
            ['code' => 'A090407', 'name' => 'SME Bank'],
            ['code' => 'A090408', 'name' => 'Uda Holding Berhad'],
            ['code' => 'A090409', 'name' => 'Perbadanan Nasional Berhad'],
            ['code' => 'A090410', 'name' => 'Amanah Ikhtiar Malaysia'],
        ],
    ],
    '010' => [
        'name' => 'Sains, Teknologi dan Inovasi',
        'agencies' => [
            ['code' => 'K100100', 'name' => 'Kementerian Sains, Teknologi dan Inovasi (MOSTI)'],
            ['code' => 'A100101', 'name' => 'Jabatan Kimia Malaysia'],
            ['code' => 'A100102', 'name' => 'Agensi Angkasa Malaysia'],
        ],
    ],
    '011' => [
        'name' => 'Perkhidmatan Jagaan Kesihatan',
        'agencies' => [
            ['code' => 'K110100', 'name' => 'Kementerian Kesihatan (KKM)'],
            ['code' => 'A110101', 'name' => 'Hospital Kuala Lumpur'],
            ['code' => 'A110102', 'name' => 'Hospital Raja Permaisuri Bainun, Perak'],
            ['code' => 'A110103', 'name' => 'Hospital Rembau, Negeri Sembilan'],
            ['code' => 'A110104', 'name' => 'Hospital Bera, Pahang'],
            ['code' => 'A110105', 'name' => 'Hospital Cyberjaya, Selangor'],
            ['code' => 'A110106', 'name' => 'Hospital Port Dickson, Negeri Sembilan'],
            ['code' => 'A110107', 'name' => 'Hospital Raja Perempuan Zainab II, Kelantan'],
            ['code' => 'A110108', 'name' => 'Hospital Tengku Ampuan Afzan, Pahang'],
            ['code' => 'A110109', 'name' => 'Hospital Tuanku Jaáfar, Negeri Sembilan'],
            ['code' => 'A110110', 'name' => 'Hospital Melaka, Melaka'],
            ['code' => 'A110111', 'name' => 'Hospital Tengku Permaisuri Norashikin Kajang, Selangor'],
            ['code' => 'A110112', 'name' => 'Hospital Queen Elizabeth II, Sabah'],
            ['code' => 'A110113', 'name' => 'Hospital Putrajaya, W.P Putrajaya'],
            ['code' => 'A110114', 'name' => 'Hospital Sungai Buloh, Selangor'],
            ['code' => 'A110115', 'name' => 'Hospital Sultan Idris Shah, Serdang, Selangor'],
            ['code' => 'A110116', 'name' => 'Hospital Bentong, Pahang'],
            ['code' => 'A110117', 'name' => 'Hospital Umum Sarawak, Sarawak'],
            ['code' => 'A110118', 'name' => 'Hospital Seberang Jaya, Pulau Pinang'],
            ['code' => 'A110119', 'name' => 'Hospital Sultanah Aminah, Johor'],
            ['code' => 'A110120', 'name' => 'Hospital Tengku Ampuan Rahimah, Klang, Selangor'],
            ['code' => 'A110121', 'name' => 'Institut Kanser Negara (IKN)'],
            ['code' => 'A110122', 'name' => 'Pejabat Timbalan Ketua Pengarah Kesihatan (Perubatan)'],
            ['code' => 'A110123', 'name' => 'Pejabat Timbalan Ketua Pengarah Kesihatan (Kesihatan Awam)'],
            ['code' => 'A110124', 'name' => 'Pejabat Timbalan Ketua Pengarah Kesihatan(Penyelidikan dan Sokongan Teknikal)'],
            ['code' => 'A110125', 'name' => 'Pejabat Timbalan Ketua Pengarah Kesihatan (Kesihatan Pergigian)'],
            ['code' => 'A110126', 'name' => 'Pejabat Timbalan Ketua Pengarah Kesihatan (Perkhidmatan Farmasi)'],
            ['code' => 'A110127', 'name' => 'Pejabat Timbalan Ketua Pengarah Kesihatan (Keselamatan dan Kualiti Makanan)'],
            ['code' => 'A110128', 'name' => 'Institut Kesihatan Negara (NIH)'],
            ['code' => 'A110129', 'name' => 'ProtectHealth Corporation Sdn. Bhd.'],
            ['code' => 'A110130', 'name' => 'Institut Jantung Negara Sdn. Bhd.'],
        ],
    ],
];
